---
version: "3.8"
services:
  kafka:
    image: "docker.io/bitnami/kafka:3.6.0"
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_BROKER_RACK=local
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LOG_CLEANER_ENABLE=true
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=300000
      - KAFKA_CFG_LOG_SEGMENT_BYTES=209715200
      - KAFKA_CFG_NUM_IO_THREADS=8
      - KAFKA_CFG_NUM_NETWORK_THREADS=112
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_NUM_REPLICA_FETCHERS=4
      - KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR=1
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES=102400
      - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=104857600
      - KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES=102400
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_NUM_PARTITIONS=16
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1

  order-monolith:
    image: "order:0.0.1-SNAPSHOT"
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - OTEL_JAVAAGENT_ENABLED=true
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_METRICS_EXPORTER=none
      - OTEL_SERVICE_NAME=order

  notification-service:
    image: "notification:0.0.1-SNAPSHOT"
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - OTEL_JAVAAGENT_ENABLED=true
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_METRICS_EXPORTER=none
      - OTEL_SERVICE_NAME=notification

  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"
